workflows:
  android:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        - key: ANDROID_HOME
          value: /opt/android-sdk-linux
    steps:
      - checkout
      - run:
          name: Install NPM dependencies
          command: |
            npm install
      - run:
          name: Install Android dependencies
          command: |
            npx cap sync android
            cd android && ./gradlew clean
      - run:
          name: Build Android App
          command: |
            cd android && ./gradlew assembleRelease

  ios:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        - key: XCODE_WORKSPACE
          value: ios/App.xcworkspace
    steps:
      - checkout
      - run:
          name: Install NPM dependencies
          command: |
            npm install
      - run:
          name: Install iOS dependencies
          command: |
            npx cap sync ios
            cd ios && pod install
      - run:
          name: Build iOS App
          command: |
            xcodebuild -workspace ios/App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath $CI_BUILD_DIR/App.xcarchive
