workflows:
  ionic-capacitor-ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: EPG LLC
    environment:
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: 6744694610
        PROVISIONING_PROFILE_PATH: "ios/provisioning/EPG_Pulse_App_Store.mobileprovision"
      node: 20.11.1
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install
      - name: Cocoapods installation
        script: |
          cd ios/App && pod install
      - name: Compile web code to dist folder
        script: npm run build
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap sync
      - name: Debug provisioning profile path
        script: |
          echo "Checking provisioning profile path..."
          ls -l "$PROVISIONING_PROFILE_PATH" || echo "File not found"
      - name: Set up provisioning profile
        script: |
          echo "Setting up provisioning profile..."
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$PROVISIONING_PROFILE_PATH" ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "Listing provisioning profiles after copying..."
          ls -l ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Extract provisioning profile UUID
        script: |
          echo "Extracting provisioning profile UUID..."
          PROVISIONING_PROFILE_UUID=$(security cms -D -i "$PROVISIONING_PROFILE_PATH" | plutil -extract UUID xml1 -o - - | grep -o "[0-9A-F-]\{36\}")
          if [ -z "$PROVISIONING_PROFILE_UUID" ]; then
          echo "Failed to extract UUID from $PROVISIONING_PROFILE_PATH"
          exit 1
          fi
          echo "Extracted UUID: $PROVISIONING_PROFILE_UUID"
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APP_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          cd $CM_BUILD_DIR/ios/App
          PROVISIONING_PROFILE_UUID=$(grep -a -E 'UUID' "$PROVISIONING_PROFILE_PATH" | grep -o "[0-9A-F-]\{36\}")
          echo "Using provisioning profile UUID: $PROVISIONING_PROFILE_UUID"
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "build/App.xcarchive" \
            -configuration Release \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution: Estim8te LLC (P5806F64US)" \
            PROVISIONING_PROFILE="$PROVISIONING_PROFILE_UUID" \
            archive
          xcodebuild -exportArchive \
            -archivePath "build/App.xcarchive" \
            -exportPath "build/ipa" \
            -exportOptionsPlist "$CM_BUILD_DIR/ios/exportOptions.plist"
    artifacts:
      - ios/App/build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData//Build//*.app
      - $HOME/Library/Developer/Xcode/DerivedData//Build//*.dSYM
    publishing:
      email:
        recipients:
          - ognen@brand-boost.agency
        notify:
          success: false
          failure: false
      app_store_connect:
        auth: integration
        submit_to_app_store: false