workflows:
  ios_build:
    name: iOS Build
    max_build_duration: 60
    environment:
      groups:
        - ios_credentials
      node: latest
      xcode: latest
    scripts:
      - name: Install NPM dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build  # Ensure web assets are built (creates ./dist)
      - name: Install iOS dependencies
        script: |
          npx cap sync ios  # Syncs web assets and generates Podfile
          cd ios/App && pod install  # Run pod install in the correct directory
      - name: Set up signing files
        script: |
          mkdir -p ~/certs
          cp certificate.p12 ~/certs/certificate.p12
          cp auth.p8 ~/certs/auth.p8
          cp epg_pulse.mobileprovision ~/certs/epg_pulse.mobileprovision
      - name: Build iOS App
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/App.xcarchive
    artifacts:
      - ios/build/App.xcarchive/Products/Applications/App.app
    publishing:
      email:
        recipients:
          - rob@epg.build
        notify:
          success: true
          failure: true