workflows:
  ionic-capacitor-ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: EPG LLC
    environment:
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"  # Updated to be relative to ios/App directory
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: 6744694610
      node: 20.11.1
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - CM_PULSEPROFILE
        certificates:
          - CM_CERTIFICATE
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install
      - name: Cocoapods installation
        script: |
          cd ios/App && pod install
      - name: Compile web code to dist folder
        script: |
          npm run build
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap sync
      - name: Debug provisioning profiles and certificates
        script: |
          echo "Listing provisioning profiles..."
          ls -l ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "No profiles found"
          echo "Listing available certificates in keychain..."
          security find-identity -v -p codesigning
      - name: Show build settings
        script: |
          cd ios/App
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -showBuildSettings
      - name: Increment build number
        script: |
          cd ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APP_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          cd ios/App
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "build/App.xcarchive" \
            -configuration Release \
            archive
          xcodebuild -exportArchive \
            -archivePath "build/App.xcarchive" \
            -exportPath "build/ipa" \
            -exportOptionsPlist "$CM_BUILD_DIR/ios/exportOptions.plist"
    artifacts:
      - ios/App/build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - ognen@brand-boost.agency
        notify:
          success: false
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false