workflows:
  ionic-capacitor-ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: EPG LLC
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: 6744694610
      node: 20.11.1
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - CM_PULSEPROFILE
        certificates:
          - CM_CERTIFICATE
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Clean npm dependencies
        script: |
          rm -rf node_modules package-lock.json
      - name: Install npm dependencies for Ionic project
        script: |
          npm install
      - name: Clean Pods cache
        script: |
          cd ios/App && rm -rf Pods && rm -f Podfile.lock
      - name: Cocoapods installation
        script: |
          cd ios/App && pod install --verbose
      - name: Compile web code to dist folder
        script: |
          npm run build
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap sync
      - name: Debug workspace file existence
        script: |
          echo "Checking for Xcode workspace file..."
          ls -l $XCODE_WORKSPACE || echo "Xcode workspace file not found"
      - name: Debug podspec file for CapacitorDevice
        script: |
          echo "Checking for CapacitorDevice podspec..."
          ls -l ../../node_modules/@capacitor/device/ios/CapacitorDevice.podspec || echo "CapacitorDevice podspec not found"
      - name: Debug provisioning profiles and certificates
        script: |
          echo "Listing provisioning profiles..."
          ls -l ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "No profiles found"
          echo "Listing available certificates in keychain..."
          security find-identity -v -p codesigning
      - name: Debug provisioning profile details
        script: |
          echo "Checking provisioning profile details..."
          for profile in ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision; do
            security cms -D -i "$profile" | grep -A 1 "Name\|TeamIdentifier\|Entitlements\|UUID"
          done
      - name: Debug bundle ID in Xcode project
        script: |
          echo "Checking bundle ID in Xcode project..."
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -showBuildSettings | grep PRODUCT_BUNDLE_IDENTIFIER
      - name: Show build settings
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -showBuildSettings
      - name: Increment build number
        script: |
          cd ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APP_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Create export_options.plist for App Store distribution
        script: |
          cd ios/App
          cat <<EOF > export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>P5806F64US</string>
          </dict>
          </plist>
          EOF
      - name: Build ipa for distribution
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -archivePath "build/App.xcarchive" \
            -configuration Release \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=P5806F64US \
            PROVISIONING_PROFILE=y3rr_xs_ \
            archive
          xcodebuild -exportArchive \
            -archivePath "build/App.xcarchive" \
            -exportPath "build/ipa" \
            -exportOptionsPlist "export_options.plist"
    artifacts:
      - ios/App/build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - ognen@brand-boost.agency
        notify:
          success: false
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false