workflows:
  ios_build:
    name: iOS Build
    max_build_duration: 60
    environment:
      groups:
        - ios_credentials  # Still good to keep this for other values like API key if needed
      node: latest
      xcode: latest
    scripts:
      - name: Install NPM dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Install iOS dependencies
        script: |
          npx cap sync ios
          cd ios/App && pod install
      - name: Set up signing files
        script: |
          ls -l ./certificate.p12 ./auth.p8 ./epg_pulse.mobileprovision
          security cms -D -i ./epg_pulse.mobileprovision > profile_details.plist
          cat profile_details.plist
      - name: Set up keychain and import certificate
        script: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import ./certificate.p12 -k build.keychain -P "EPG!!build89" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID=$(security cms -D -i ./epg_pulse.mobileprovision | grep -A1 '<key>UUID</key>' | grep '<string>' | sed -E 's/.*<string>(.*)<\/string>.*/\1/')
          cp ./epg_pulse.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision
      - name: Build iOS App
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=P58Q6F64US \
            PROVISIONING_PROFILE_SPECIFIER=$PROFILE_UUID \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            archive
    artifacts:
      - $CM_BUILD_DIR/App.xcarchive
      - profile_details.plist
    publishing:
      email:
        recipients:
          - ognen@brand-boost.agency
        notify:
          success: true
          failure: true
